Repository CMPT-2276-001-Douglas-College/hw1-Phuong-Matthew-Abidali, pull requests merged in 2023-02, with the labels that each got.

#3 Added name Abidali
  README.md
Labels: good first issue

#5 added empty Visual Studio Project
  .gitignore
  Visual Studio Project files/HamiltonApportionment(part2)/HamiltonApportionment(part2).sln
  Visual Studio Project files/HamiltonApportionment(part2)/HamiltonApportionment(part2)/HamiltonApportionment(part2).vcxproj
  Visual Studio Project files/HamiltonApportionment(part2)/HamiltonApportionment(part2)/HamiltonApportionment(part2).vcxproj.filters
  Visual Studio Project files/HamiltonApportionment(part2)/HamiltonApportionment(part2)/HamiltonApportionment(part2).vcxproj.user
  Visual Studio Project files/HamiltonApportionment(part2)/HamiltonApportionment(part2)/Source.cpp
Labels: Feature, Setup

#26 Release/0.1.0
  README.md
Labels: Release

#27 Added read function
  Visual Studio Project files/HamiltonApportionment(part2)/HamiltonApportionment(part2).vcxproj
  Visual Studio Project files/HamiltonApportionment(part2)/HamiltonApportionment(part2).vcxproj.filters
  Visual Studio Project files/HamiltonApportionment(part2)/HamiltonApportionment(part2).vcxproj.user
  Visual Studio Project files/HamiltonApportionment(part2)/HamiltonApportionment(part2)/Source.cpp
  Visual Studio Project files/HamiltonApportionment(part2)/Source.cpp
Labels: Feature

#44 Fixed Sln file bug
  Visual Studio Project files/HamiltonApportionment(part2).sln
  Visual Studio Project files/HamiltonApportionment(part2).vcxproj
  Visual Studio Project files/HamiltonApportionment(part2).vcxproj.filters
  Visual Studio Project files/HamiltonApportionment(part2).vcxproj.user
  Visual Studio Project files/Source.cpp
  Visual Studio Project files/x64/Debug/Hamilton.49fa2b44.tlog/CL.command.1.tlog
  Visual Studio Project files/x64/Debug/Hamilton.49fa2b44.tlog/CL.read.1.tlog
  Visual Studio Project files/x64/Debug/Hamilton.49fa2b44.tlog/CL.write.1.tlog
  Visual Studio Project files/x64/Debug/Hamilton.49fa2b44.tlog/HamiltonApportionment(part2).lastbuildstate
  Visual Studio Project files/x64/Debug/Hamilton.49fa2b44.tlog/link.command.1.tlog
  Visual Studio Project files/x64/Debug/Hamilton.49fa2b44.tlog/link.read.1.tlog
  Visual Studio Project files/x64/Debug/Hamilton.49fa2b44.tlog/link.write.1.tlog
  Visual Studio Project files/x64/Debug/HamiltonApportionment(part2).Build.CppClean.log
  Visual Studio Project files/x64/Debug/HamiltonApportionment(part2).exe.recipe
  Visual Studio Project files/x64/Debug/HamiltonApportionment(part2).ilk
  Visual Studio Project files/x64/Debug/HamiltonApportionment(part2).log
  Visual Studio Project files/x64/Debug/HamiltonApportionment(part2).pdb
  Visual Studio Project files/x64/Debug/HamiltonApportionment(part2).vcxproj.FileListAbsolute.txt
  Visual Studio Project files/x64/Debug/vc143.idb
  Visual Studio Project files/x64/Debug/vc143.pdb
Labels: bug

#46 Added data validation and rep input request
  Visual Studio Project files/Assignment01Part02/Source.cpp
  Visual Studio Project files/Assignment01Part02/x64/Debug/Assignme.fda71432.tlog/link.read.1.tlog
  Visual Studio Project files/Assignment01Part02/x64/Debug/Assignme.fda71432.tlog/link.write.1.tlog
  Visual Studio Project files/Assignment01Part02/x64/Debug/Assignment01Part02.ilk
  Visual Studio Project files/Assignment01Part02/x64/Debug/Assignment01Part02.log
  Visual Studio Project files/Assignment01Part02/x64/Debug/Assignment01Part02.pdb
  Visual Studio Project files/Assignment01Part02/x64/Debug/vc143.idb
  Visual Studio Project files/Assignment01Part02/x64/Debug/vc143.pdb
  Visual Studio Project files/HamiltonApportionment(part2).sln
  Visual Studio Project files/HamiltonApportionment(part2).vcxproj
  Visual Studio Project files/HamiltonApportionment(part2).vcxproj.filters
  Visual Studio Project files/HamiltonApportionment(part2).vcxproj.user
  Visual Studio Project files/Source.cpp
  Visual Studio Project files/x64/Debug/Hamilton.49fa2b44.tlog/CL.command.1.tlog
  Visual Studio Project files/x64/Debug/Hamilton.49fa2b44.tlog/CL.read.1.tlog
  Visual Studio Project files/x64/Debug/Hamilton.49fa2b44.tlog/CL.write.1.tlog
  Visual Studio Project files/x64/Debug/Hamilton.49fa2b44.tlog/HamiltonApportionment(part2).lastbuildstate
  Visual Studio Project files/x64/Debug/Hamilton.49fa2b44.tlog/link.command.1.tlog
  Visual Studio Project files/x64/Debug/Hamilton.49fa2b44.tlog/link.read.1.tlog
  Visual Studio Project files/x64/Debug/Hamilton.49fa2b44.tlog/link.write.1.tlog
  Visual Studio Project files/x64/Debug/HamiltonApportionment(part2).Build.CppClean.log
  Visual Studio Project files/x64/Debug/HamiltonApportionment(part2).exe.recipe
  Visual Studio Project files/x64/Debug/HamiltonApportionment(part2).ilk
  Visual Studio Project files/x64/Debug/HamiltonApportionment(part2).log
  Visual Studio Project files/x64/Debug/HamiltonApportionment(part2).pdb
  Visual Studio Project files/x64/Debug/HamiltonApportionment(part2).vcxproj.FileListAbsolute.txt
  Visual Studio Project files/x64/Debug/vc143.idb
  Visual Studio Project files/x64/Debug/vc143.pdb
Labels: duplicate, Feature

#47 pulled updated solution and added writeToFile function to it
  Visual Studio Project files/Assignment01Part02/writeToFile.cpp
Labels: Feature

#63 Added calling write in main and refined Input/Output
  Visual Studio Project files/Assignment01Part02/HamiltonAlgorithm.h
  Visual Studio Project files/Assignment01Part02/Source.cpp
  Visual Studio Project files/Assignment01Part02/writeToFile.h
  Visual Studio Project files/Assignment01Part02/x64/Debug/Assignme.fda71432.tlog/Assignment01Part02.lastbuildstate
  Visual Studio Project files/Assignment01Part02/x64/Debug/Assignme.fda71432.tlog/CL.read.1.tlog
  Visual Studio Project files/Assignment01Part02/x64/Debug/Assignme.fda71432.tlog/CL.write.1.tlog
  Visual Studio Project files/Assignment01Part02/x64/Debug/Assignme.fda71432.tlog/link.read.1.tlog
  Visual Studio Project files/Assignment01Part02/x64/Debug/Assignme.fda71432.tlog/link.write.1.tlog
  Visual Studio Project files/Assignment01Part02/x64/Debug/Assignment01Part02.exe.recipe
  Visual Studio Project files/Assignment01Part02/x64/Debug/Assignment01Part02.ilk
  Visual Studio Project files/Assignment01Part02/x64/Debug/Assignment01Part02.log
  Visual Studio Project files/Assignment01Part02/x64/Debug/Assignment01Part02.pdb
  Visual Studio Project files/Assignment01Part02/x64/Debug/vc143.idb
  Visual Studio Project files/Assignment01Part02/x64/Debug/vc143.pdb
Labels: bug

#71 Final Submission of Hamilton's Algorithm
  README.md
Labels: Final Commit
